---
ID: "e741c1a4-7126-486d-a97f-adfd4fec7a6a"
Parent: "c293de50-77a2-4abc-99fe-2f0823879180"
Template: "c293de50-77a2-4abc-99fe-2f0823879180"
Path: /sitecore/templates/MVC Tutorial/Home/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {76036F5E-CBCE-46D1-AF0A-4143F9B557AA}
    {A87A00B1-E6DB-45AB-8B54-636FEC3B5523}
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{14030E9F-CE92-49C6-AD87-7D49B50E42EA}">
        <r
          ds=""
          id="{885B8314-7D8C-4CBB-8000-01421EA8F406}"
          par=""
          ph="main"
          uid="{43222D12-08C9-453B-AE96-D406EBB95126}" />
        <r
          ds=""
          id="{CE4ADCFB-7990-4980-83FB-A00C1E3673DB}"
          par=""
          ph="/main/centercolumn"
          uid="{CF044AD9-0332-407A-ABDE-587214A2C808}" />
        <r
          ds=""
          id="{493B3A83-0FA7-4484-8FC9-4680991CF743}"
          par=""
          ph="/main/centercolumn/content"
          uid="{B343725A-3A93-446E-A9C8-3A2CBD3DB489}" />
      </d>
      <d
        id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
        l="{14030E9F-CE92-49C6-AD87-7D49B50E42EA}">
        <r
          ds=""
          id="{493B3A83-0FA7-4484-8FC9-4680991CF743}"
          par=""
          ph="content"
          uid="{A08C9132-DBD1-474F-A2CA-6CA26A4AA650}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "14b703d3-17c9-4cf5-9b8b-3e05cd83a153"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20061024T104300
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\Admin
